apiVersion: v1
kind: Service
metadata:
  name: web-app-service
spec:
  type: LoadBalancer
  selector:
    app: web-app
  ports:
  - name: backend
    port: 3000
    targetPort: 3000
  - name: frontend
    port: 80
    targetPort: 80
